on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Publish tag to npm
      if: contains(github.ref, 'tags')
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}